export const UPDATE_USERNAME = 'UPDATE_USERNAME'
export const UPDATE_PLAYER_ONE_NAME = 'UPDATE_PLAYER_ONE_NAME'
export const UPDATE_PLAYER_TWO_NAME = 'UPDATE_PLAYER_TWO_NAME'

export const UPDATE_PLAYER_ONE_IMAGE = 'UPDATE_PLAYER_ONE_IMAGE'
export const UPDATE_PLAYER_TWO_IMAGE = 'UPDATE_PLAYER_TWO_IMAGE'

export const FETCH_RESULT_BATTLE_REQUEST = 'FETCH_RESULT_RESULT_REQUEST'
export const FETCH_RESULT_BATTLE_SUCCESS = 'FETCH_RESULT_RESULT_SUCCESS'
export const FETCH_RESULT_BATTLE_FAILURE = 'FETCH_RESULT_RESULT_FAILURE'
