export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE'
export const FETCH_POPULAR_REPOS_REQUEST = 'FETCH_POPULAR_REPOS_REQUEST'
export const FETCH_POPULAR_REPOS_SUCCESS = 'FETCH_POPULAR_REPOS_SUCCESS'
export const FETCH_POPULAR_REPOS_FAILURE = 'FETCH_POPULAR_REPOS_FAILURE'
