export const UPDATE_LANGUAGE: string = 'UPDATE_LANGUAGE'
export const FETCH_POPULAR_REPOS_REQUEST: string = 'FETCH_POPULAR_REPOS_REQUEST'
export const FETCH_POPULAR_REPOS_SUCCESS: string = 'FETCH_POPULAR_REPOS_SUCCESS'
export const FETCH_POPULAR_REPOS_FAILURE: string = 'FETCH_POPULAR_REPOS_FAILURE'
